### ISSUE TITLE
Authentication is not working.

### ISSUE THREAD

**Issue by zeroalphat** [shellhub-io/shellhub#32] opened 2020-02-21 05:11 UTC
# Authentication is not working

I ran shellhub on Mac. However, Web authentication has caused a 401 error, and I cannot log in. I infer the web app sent a user name and password from the login screen to the API server.

<img width="443" alt="Screen Shot 2020-02-21 at 14 03 03" src="https://user-images.githubusercontent.com/22779960/75005815-f1735200-54b2-11ea-8250-5f1fbed73591.png">
<img width="1669" alt="Screen Shot 2020-02-21 at 14 00 59" src="https://user-images.githubusercontent.com/22779960/75005835-0223c800-54b3-11ea-8e20-e3157141430c.png">

## environment

```
$ docker --version
Docker version 19.03.5, build 633a0ea
$ docker-compose --version
docker-compose version 1.25.4, build 8d51620a
```

**Comment by gustavosbarreto** [comment] 2020-02-23 16:41
What version of shellhub are you using?

**Comment by zeroalphat** [comment] 2020-02-24 07:05
I'm using shellhub version v0.0.5

**Comment by gustavosbarreto** [comment] 2020-02-24 13:33
> I'm using shellhub version v0.0.5

Can you please ensure that user exists?

In the ShellHub working dir please run the following command (and paste output here):

```
docker-compose exec mongo mongo --eval "db.users.find()" main
```

**Comment by zeroalphat** [comment] 2020-03-05 02:07
I'm sorry for the late reply.
The user I added with the ```./bin/add-user [username] [userpassword]``` command was confirmed.
```
$ docker-compose exec mongo mongo --eval "db.users.find()" main
MongoDB shell version v3.4.19
connecting to: mongodb://127.0.0.1:27017/main
MongoDB server version: 3.4.19
{ "_id" : ObjectId("5e4f64753459cbdb1dce2e42"), "username" : "hoge", "password" : "7042f999013fdb493c1c2d12510389948ddc74af61cb1aea8f6c4ae69b4a3061", "tenant_id" : "5C911130-C112-4082-86B1-8AF139ECF3CF" }
```

**Comment by chamaloriz** [comment] 2020-03-20 10:57
same issue here

**Comment by chamaloriz** [comment] 2020-03-20 11:12
Same error here and the user is added to the db
I'm on the v0.2.0

**Comment by chamaloriz** [comment] 2020-03-20 17:20
- So the problem is that on mac os echo -n &2 returns -n &2 => 
https://apple.stackexchange.com/questions/173836/why-echo-n-doesnt-work-in-this-script-on-mac-terminal

to FIX => replace in bin/add-user 

PASSWORD=`echo -n $2 | sha256sum | awk '{ print $1 }'`

to 

PASSWORD=`printf $2 | sha256sum | awk '{ print $1 }'`

**Comment by gustavosbarreto** [comment] 2020-03-20 17:28
Fixed in https://github.com/shellhub-io/shellhub/commit/ce41798fac3033639ec14c1733b9eb7346083943

**Closed by gustavosbarreto** 2020-03-20 17:28 UTC
