### ISSUE TITLE
the agent docker was stuck on dns lookup when there was connectivity  problem

### ISSUE THREAD

**Issue by j3dd4h** [shellhub-io/shellhub#593] opened 2020-12-29 09:18 UTC
It seem the agent docker was stuck on dns lookup and required restart the agent docker to solved.

`2020/12/29 07:39:52 [DEBUG] GET https://sh.mydomain.net:443/info: retrying in 30s (2147483423 left)
2020/12/29 07:40:22 [ERR] GET https://sh.mydomain.net:443/info request failed: Get https://sh.mydomain.net:443/info: dial tcp: lookup sh.mydomain.net on [::1]:53: read udp [::1]:43645->[::1]:53: read: connection refused`

**Comment by otavio** [comment] 2021-01-06 17:39
@j3dd4h thank you for reporting this issue. We need to understand the environment where this issue happened.

1. What is the Linux distribution where the agent is running?
2. What is the version of the agent you are using?

**Comment by j3dd4h** [comment] 2021-01-11 22:36
Sorry for late reply
I'm using docker (shellhubio/agent:v0.4.2) on ubuntu 20.04

**Comment by otavio** [comment] 2021-01-13 21:37
@j3dd4h can you try to reproduce this error with master?

**Comment by shawn111** [comment] 2021-01-16 09:59
@j3dd4h is it possible your env problem? like firewall config.

**Comment by otavio** [comment] 2021-01-18 14:39
We couldn't reproduce the issue. Please provide more information on how to reproduce it or a way to debug the case. For now, we'll be closing this.

**Comment by jcarrus** [comment] 2021-07-06 19:12
Hi everyone, I also just ran into this issue on v0.7.0.

I'm running the shellhub agent as a docker container on an Alpine Linux host (3.14). The condition arose when we moved the host from one network to another. There seems to be a race condition where docker injects the DNS settings into the shellhub container on boot, but then later during the boot process, when the host negotiates DNS with the DHCP server, those new settings don't propagate to the docker client.

Restarting the container or the host resolves the issue.

So, it would be great if a flag/environment variable could be added to the effect of `STOP_ON_CONNECTION_ERROR` which would cause the container to quit if a connection couldn't be established to the shellhub server. That (coupled with passing `--restart=always/unless-stopped` to the docker daemon) would help us avoid this issue in the future.

What do others think of this suggestion?

(love the product by the way!)

**Comment by otavio** [comment] 2021-07-06 19:19
@jcarrus is this something you can reproduce easily?

**Comment by jcarrus** [comment] 2021-07-06 19:21
Hi @otavio , it's a bit time consuming to reproduce (I modify the settings on my router and then restart everything), but it does reproduce reliably for me. I'm happy to test any code changes.

**Comment by otavio** [comment] 2021-07-06 19:32
@jcarrus I am wondering how it could be handled. This seems to be a Docker issue as it should propagate the new DNS server entries to the container, but for some reason, it is not doing it.

If we restart the container, we will work around it, but at the same time, it'd be kept restarting forever in case there is no network available. This doesn't sound right to me.

**Comment by jcarrus** [comment] 2021-07-06 19:43
@otavio that's a good point. You are totally right that it's likely a docker issue (unless the agent code or Go is somehow caching the network settings, but I'm not seeing any evidence of that).

That being said, it would be helpful to have a way to address this. I'd be totally fine for a hardcoded retry period or a configurable one. Something to the effect of `NETWORK_RETRY_PERIOD=300`, which would indicate that after 300 seconds of no connection, the container should restart.

It would be really great to have an exponential backoff, but I'm not sure that's possible since the container itself would have to fully restart to fix this networking bug.

So anyway, maybe the simplest would be to instead add a configuration option:

---

=> `SHELLHUB_NETWORK_TIMEOUT`

If a network connection is not established to the server after `SHELLHUB_NETWORK_TIMEOUT` seconds, quit the shellhub process. If unset, the process will retry forever.

**Comment by otavio** [comment] 2021-07-06 19:55
@jcarrus I am wondering how we could reproduce this, so we could try to find the culprit of the issue. Do you have a set of steps we can use to try to reproduce it here?

**Comment by jcarrus** [comment] 2021-07-06 21:05
@otavio After looking into this a bit more, this can be trivially reproduced by modifying the host's `/etc/resolve.conf` file, restarting the shellhub container, and then changing the hosts `/etc/resolve.conf` file back. You'll notice that the shellhub container still can't connect.

This is the equivalent of booting the host on a new network. The docker container starts with the old `/etc/resolv.conf` settings from the previous network, and then when the host's `/etc/resolv.conf` updates, the changes are not propogated to the container.

Running `docker inspect shellhub` and then inspecting the `ResolvConfPath` key in the resulting JSON will show that the host's `/etc/resolv.conf` file is copied into the container on container start and is not updated with future changes.

---

It does seem like this is expected behavior on the side of docker: https://docs.docker.com/config/containers/container-networking/#dns-services

And the workaround seems to be to bind mount the host /etc/resolve.conf into the container, which.... could be a resolution to this, but given how seamless the Shellhub experience has been, I think it would be great if this could be handled by Shellhub.

---

What do you think?

**Comment by otavio** [comment] 2021-07-06 21:17
I think it should be mapped as a volume, so if it is changed, it is reflected inside the container. Does it work?

**Comment by otavio** [comment] 2021-07-06 21:18
It could be handled by the upgrade process and the installation script ;-)

**Comment by jcarrus** [comment] 2021-07-06 21:37
@otavio yes! I can confirm that mounting `/etc/resolv.conf` into the container allows the container to recover from this error.

And ahh, I see all of the other mounts in the installation script now, seems like that's the right place to drop this change into.

**Comment by otavio** [comment] 2021-07-06 23:56
How about it being your first PR @jcarrus?

**Comment by jcarrus** [comment] 2021-07-07 19:04
@otavio sure, I'll take a look in the next few days and tag you in the PR

**Comment by otavio** [comment] 2021-07-07 19:11
Awesome @jcarrus :-) thanks for your help in figuring out the root cause of the issue.

**Closed** 2021-07-20 18:47 UTC
Labels: kind/bug
