### ISSUE TITLE
Agent: High CPU usage after closing a terminal

### ISSUE THREAD

**Issue by S-Chinthana** [shellhub-io/shellhub#73] opened 2020-04-13 03:34 UTC
Hi, I manage to install ShellHub agent into a Raspberry pi 4 using Docker and it is working fine. But after I open an SSH terminal from ShellHub web UI or Putty and close the terminal, then suddenly Raspberry pi CPU usage jumps up to 100%(one whole core is using ShellHub agent[/bin/agent] ), If I Open and closes another terminal again CPU usage Jumps up to 200% (two cores are at 100%). If I do it again and again. All CPU cores are 100% uses by ShellHub agents, until I _kill_ one of **ShellHub agent process** or restart the **docker container**. Any opinion about this issue??

![Capture_1](https://user-images.githubusercontent.com/42964107/79089253-212c3100-7d63-11ea-9114-f44e0bd2f4f5.PNG)
-While using a terminal-

![Capture_2](https://user-images.githubusercontent.com/42964107/79089255-225d5e00-7d63-11ea-90fa-47c968fee47c.PNG)
-After closing one terminal-

![Capture_3](https://user-images.githubusercontent.com/42964107/79089257-22f5f480-7d63-11ea-8bb9-d60473762ce7.PNG)
-after closing four or more terminals-

**Comment by gustavosbarreto** [comment] 2020-04-17 13:44
I confirm this issue also on Arch Linux

**Comment by gustavosbarreto** [comment] 2020-04-17 13:56
The high CPU usage is caused by the "keep-alive polling" that keep running even while the connection is closed.

https://github.com/shellhub-io/shellhub/blob/6b1cda6761c38afa4e2c2fa536f4e5e24793f2c6/agent/sshserver.go#L96-L106

**Comment by gustavosbarreto** [comment] 2020-04-17 19:38
Hey @S-Chinthana 
Thanks. It was fixed on master branch but it is not yet available in the latest public release.
I need to release an update.

**Comment by S-Chinthana** [comment] 2020-04-20 06:27
Thanks a lot, @gustavosbarreto . really appreciate your dedication!

**Comment by S-Chinthana** [comment] 2020-04-20 11:06
@gustavosbarreto  I clone the master branch got the latest code on it, and I run the ShellHub container. but still, have the same issue. is there anything should I do in the agent side (Raspberry pi side )?

**Comment by gustavosbarreto** [comment] 2020-04-20 17:59
@S-Chinthana You need to update the device's agent to the latest version v0.2.4

How many devices are you currently managing with ShellHub? Depending on how many It may be very tedious to manually update each device.

**Closed by gustavosbarreto** 2020-04-20 17:59 UTC
Labels: bug
