### ISSUE TITLE
Using an exec command with tty allocation is identified as a shell request

### ISSUE THREAD

**Issue by benasse** [shellhub-io/shellhub#3116] opened 2023-09-19 21:08 UTC
### Description

In some cases, it may be appropriate to force the allocation of a tty during a command exec.

In this case, Shellhub interprets the request as a shell request and not as an exec request.

## Steps to reproduce
Run:
```ssh user@namespace.device@shellhub -tt 'ls'```

## Expected Result
I see the output of the command `ls`

## Actual Result
An interactive shell is started.

### Edition

Community

### Version

master

**Comment by benasse** [comment] 2023-09-20 21:14
From what I've found, this part of the code needs to be optimized: https://github.com/shellhub-io/shellhub/blob/master/ssh/session/session.go#L99

I'll see if I can come up with a solution in the next few days. 

This project is a bit complex and I'm a beginner in golang, so don't hesitate if you have a quick and easy solution!

**Comment by heiytor** [comment] 2023-09-21 00:54
Hi @benasse,

Thank you for bringing this!

The root cause of this issue is how the `handlePty` function treats the `-t` and `-tt` flag. Rather than recognizing them as commands, it sets `isPty` to true, causing `s.Client.Command()` to overlook the flag:
```go
pty, _, isPty := s.Client.Pty()
[...]
commands := s.Client.Command() // Commands will not contain "-tt" flag
var cmd string
if len(commands) != 0 {
	cmd = commands[0] // Commands[0] is "ls" in your case
}
```

Consequently, the switch statement you provided matches the `case isPty`:
```go
switch {
case !isPty && strings.HasPrefix(cmd, SCP):
	s.Type = SCP
case !isPty && cmd != "":
	s.Type = Exec
case !isPty && metadata.RestoreRequest(ctx) == "shell":
	s.Type = HereDoc
case isPty:
	s.Type = Term
default:
	s.Type = Unk
}
```

This then results in the command being executed as a *shell* rather than an *exec*:
```go
// Within the connectSSH function
switch sess.GetType() {
case session.Term, session.Web: // <- Currently enters here
	err := shell(api, sess, sess.UID, agent, client, pty, winCh, opts)
	if err != nil {
		return ErrRequestShell
	}
case session.HereDoc:
	err := heredoc(api, sess.UID, agent, client)
	if err != nil {
		return ErrRequestHeredoc
	}
case session.Exec, session.SCP: // <- You want it to enter here
	err := exec(api, sess.UID, metadata.RestoreDevice(ctx.(gliderssh.Context)), agent, client)
	if err != nil {
		return ErrRequestExec
	}
default:
	client.Exit(255) // nolint:errcheck
	return ErrRequestUnsupported
}
```

As a temporary solution, you can modify the switch statement as follows:
```go
switch {
case !isPty && strings.HasPrefix(cmd, SCP):
	s.Type = SCP
case !isPty && cmd != "", isPty && cmd != "":
	s.Type = Exec
case !isPty && metadata.RestoreRequest(ctx) == "shell":
	s.Type = HereDoc
case isPty:
	s.Type = Term
default:
	s.Type = Unk
}
```

Please let us know if this workaround addresses your issue, and thanks for your patience! I'm currently working on a more refined solution for this.

**Comment by heiytor** [comment] 2023-09-22 17:31
Hi, @benasse,

I'm back to clarify that the "temporary solution" will, in fact, execute the command without requiring a tty. One primary reason for this is that modifying *exec* to execute the command with `RequestPty` (like *shell* does) would be a breaking change for older agent versions. I apologize for overlooking this detail in my last message.

However, I've opened a new PR #3119 to address this issue correctly. If you have any suggestions or ideas, I would appreciate your contribution.

**Comment by benasse** [comment] 2023-09-22 19:08
Hi @heiytor ,

Thank you very much for the detailed explanation, it's very interesting !

I tested the "temporary solution" and I can confirm that it works, it allows you to run the exec without pty.

I opened the ticket because I was affected by 2 use cases:
- ansible gets stuck because its command doesn't execute, due to the fact that it uses the -tt flag by defat ➡️ the temporary solution solves the problem
- being able to run a pseudo-graphical application using ncurse ( ncdu for example) ➡️ the definitive fix should solve this problem

I'll do my best to test the PR when it's finalized.
Unfortunately for the moment I can't help much with code quality, I'm in the process of self-training in golang but I'm just starting 😃

**Comment by heiytor** [comment] 2023-09-26 17:01
Fixed in PR #3119. After merge, you will be able to execute commands with a TTY, including pseudo-graphical applications like `top` and `nvim`.

**Comment by benasse** [comment] 2023-09-29 08:04
Hi @heiytor ,

I've run a few tests and everything works fine for the pty !

However, I don't know if it's related to this evolution, but I detect a regression concerning the exit codes.
When I run a command (with or without pty), it executes correctly but the output code is 255. 

![image](https://github.com/shellhub-io/shellhub/assets/5676729/66f89101-e757-49f9-8c88-b09986e18123)

**Comment by heiytor** [comment] 2023-09-29 12:22
Hi, @benasse ,

Sorry for that, the issue was due to my misunderstanding of `defer`. It should be functioning correctly now:

![image](https://github.com/shellhub-io/shellhub/assets/107213601/10c4e02d-fbbe-442c-a035-61b353738b7e)

**Closed** 2023-10-11 12:57 UTC
Labels: area/ssh
