### ISSUE TITLE
working directory goes wrong after `sudo`

### ISSUE THREAD

**Issue by zhanglongqi** [shellhub-io/shellhub#411] opened 2020-09-21 03:38 UTC
![screenshot-cloud shellhub io-2020 09 21-11_34_59](https://user-images.githubusercontent.com/956693/93731257-d5798f80-fbfe-11ea-8557-f7acee2d2496.png)

**Comment by gustavosbarreto** [comment] 2020-09-21 12:17
I cannot reproduce this in Arch Linux. What operating system are you using?

**Comment by zhanglongqi** [comment] 2020-09-22 06:46
The host OS is MacOS Catalina and Linux Ubuntu 18.04, Both of them can see the issue.
The target OS is Raspbian GNU/Linux 10 (buster)

**Comment by otavio** [comment] 2020-12-03 19:53
@zhanglongqi, we couldn't reproduce this issue, but looking at the screenshot you provided might be related to the Shell profile you are using. Please provide the following information:

1. What shell are you using (bash, zsh, fish, ...)?
1. What profile settings are you using? Is it something we can replicate here?

**Comment by zhanglongqi** [comment] 2020-12-04 01:28
I use `zsh`, the theme is `ys`. all the other related zsh is default setting
`zsh 5.7.1 (arm-unknown-linux-gnueabihf)`

**Comment by otavio** [comment] 2021-01-13 21:36
@zhanglongqi, is it possible for you to test this in the current version? 

We are about to release 0.5.0, and it'd be good to know if this still happens.

**Comment by otavio** [comment] 2021-01-18 14:42
We'll be closing this as we couldn't reproduce it. Please reopen this if you still see the issue with the current release.

**Comment by zhanglongqi** [comment] 2021-04-27 05:33
I am running shellhubio/agent:v0.6.3  The issue is still there.

**Comment by gustavosbarreto** [comment] 2021-04-27 13:07
> I am running shellhubio/agent:v0.6.3 The issue is still there.

@zhanglongqi are you running on docker or source build?

**Comment by otavio** [comment] 2021-04-27 13:12
@zhanglongqi also, please provide the output of:

```sh
env
mount
```

**Comment by zhanglongqi** [comment] 2021-05-03 03:49
> > I am running shellhubio/agent:v0.6.3 The issue is still there.
> 
> @zhanglongqi are you running on docker or source build?

docker

**Comment by zhanglongqi** [comment] 2021-05-03 03:50
> @zhanglongqi also, please provide the output of:
> 
> ```shell
> env
> mount
> ```

```shell
$ env
TERM=xterm
SHELL=/usr/bin/zsh
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LANG=en_SG.UTF-8
LC_ALL=en_SG.UTF-8
LANGUAGE=en_SG.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
MAIL=/var/mail/root
LOGNAME=root
USER=root
HOME=/root
SUDO_COMMAND=/usr/bin/zsh
SUDO_USER=longqi
SUDO_UID=1001
SUDO_GID=1001
SHLVL=1
PWD=/root
OLDPWD=/host/home/longqi
ZSH=/root/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
_=/usr/bin/env



$ mount
/dev/mmcblk0p7 on / type ext4 (rw,noatime)
devtmpfs on /dev type devtmpfs (rw,relatime,size=439916k,nr_inodes=109979,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,mode=755)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
/dev/mmcblk0p6 on /boot type vfat (rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /run/user/1001 type tmpfs (rw,nosuid,nodev,relatime,size=94636k,mode=700,uid=1001,gid=1001)
overlay on /var/lib/docker/overlay2/e53bd3def616dbc870eebf20d10b8c77992ca0f94d35121617b206a01c25de1a/merged type overlay (rw,relatime,lowerdir=/var/lib/docker/overlay2/l/GUPASXDHOTP24QMIRFRB7KUUGB:/var/lib/docker/overlay2/l/X3UEE2634OWNMNHXGY2PQSTWZP:/var/lib/docker/overlay2/l/CPV3JE4QNNVRSNQHZDQZQULX4K:/var/lib/docker/overlay2/l/LQ25NEWBO75RYFXJ4IUBOWC6VA:/var/lib/docker/overlay2/l/4GVGE56UDS6PLFQI3XPTATACJJ:/var/lib/docker/overlay2/l/4BWHIIJWNTSECOVS6J64U42EGZ:/var/lib/docker/overlay2/l/VV2HUM6I52FCNUQLSYKFUHUWI7,upperdir=/var/lib/docker/overlay2/e53bd3def616dbc870eebf20d10b8c77992ca0f94d35121617b206a01c25de1a/diff,workdir=/var/lib/docker/overlay2/e53bd3def616dbc870eebf20d10b8c77992ca0f94d35121617b206a01c25de1a/work)
nsfs on /run/docker/netns/default type nsfs (rw)
gvfsd-fuse on /run/user/1001/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1001,group_id=1001)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
```

**Comment by gustavosbarreto** [comment] 2021-11-10 18:33
https://github.com/util-linux/util-linux/issues/1500

**Comment by otavio** [comment] 2021-11-10 18:37
@zhanglongqi, this issue ended being very hard to debug. We found what causes it but are still uncertain about how to fix it better. The above problem has been reported to `util-linux` where `nsenter` belongs, so we try to get to the bottom of it. Let's see what upstream tell us.

**Comment by zhanglongqi** [comment] 2021-11-11 01:15
understand

**Comment by gustavosbarreto** [comment] 2021-12-21 18:26
The fix for this issue depends on a being release of new version of util-linux.

**Closed** 2022-07-25 16:35 UTC
Labels: worksforme

**Comment by gustavosbarreto** [comment] 2022-07-25 16:37
@zhanglongqi This has been fixed and will be available in an upcoming release
